# Generated by Django 5.0.6 on 2024-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_teacher', models.CharField(max_length=20)),
                ('class_course', models.CharField(max_length=20)),
                ('class_id', models.PositiveSmallIntegerField()),
                ('class_description', models.TextField()),
                ('class_start_date', models.DateField()),
                ('class_end_date', models.DateField()),
                ('class_size', models.PositiveIntegerField()),
            ],
        ),
    ]
